apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-myapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      replica: black
  template:
    metadata:
      labels:
        app: myapp
        replica: black
    spec:
      containers:
        - name: myapp
          image: 815512685331.dkr.ecr.us-east-1.amazonaws.com/azure:latest
          ports:
            - name: http
              containerPort: 80
        
